services:
  database:
    image: postgres:14
    restart: always
    container_name: prisma-db-tax
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tax
    volumes:
      - ./db:/var/lib/postgresql/data
networks:
  tax-net:
    external: true
